package uz.muxtoriyat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAllPropertiesEquals(Reaction expected, Reaction actual) {
        assertReactionAutoGeneratedPropertiesEquals(expected, actual);
        assertReactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAllUpdatablePropertiesEquals(Reaction expected, Reaction actual) {
        assertReactionUpdatableFieldsEquals(expected, actual);
        assertReactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAutoGeneratedPropertiesEquals(Reaction expected, Reaction actual) {
        assertThat(expected)
            .as("Verify Reaction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionUpdatableFieldsEquals(Reaction expected, Reaction actual) {
        assertThat(expected)
            .as("Verify Reaction relevant properties")
            .satisfies(e -> assertThat(e.getDeviceId()).as("check deviceId").isEqualTo(actual.getDeviceId()))
            .satisfies(e -> assertThat(e.getReactionType()).as("check reactionType").isEqualTo(actual.getReactionType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionUpdatableRelationshipsEquals(Reaction expected, Reaction actual) {
        assertThat(expected)
            .as("Verify Reaction relationships")
            .satisfies(e -> assertThat(e.getArticle()).as("check article").isEqualTo(actual.getArticle()));
    }
}
