package uz.muxtoriyat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAllPropertiesEquals(Source expected, Source actual) {
        assertSourceAutoGeneratedPropertiesEquals(expected, actual);
        assertSourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAllUpdatablePropertiesEquals(Source expected, Source actual) {
        assertSourceUpdatableFieldsEquals(expected, actual);
        assertSourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAutoGeneratedPropertiesEquals(Source expected, Source actual) {
        assertThat(expected)
            .as("Verify Source auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceUpdatableFieldsEquals(Source expected, Source actual) {
        assertThat(expected)
            .as("Verify Source relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceUpdatableRelationshipsEquals(Source expected, Source actual) {
        assertThat(expected)
            .as("Verify Source relationships")
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()));
    }
}
